services:
  backend:
    build: backend
    ports:
      - "4000:4000"

  frontend:
    image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    volumes:
      - .:/workspaces:cached

    depends_on:
      - backend